# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paradox4280
email: sabawoon.shams@aol.com 
description: > # this means to ignore newlines until "baseurl:"
 Welcome to this site will not much of a website i guess it's better
 then nothing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: saba_woon4280
github_username:  Paradox4280

# Build settings
markdown: kramdown
